apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v4kmvhyq1-python
  janus-idp.io/tekton: v4kmvhyq1-python
  backstage.io/kubernetes-id: v4kmvhyq1-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v4kmvhyq1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
